spring:
  profiles:
    active: dev
#文件上传与下载
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html
#分页助手
pagehelper:
  helper-dialect: mysql
  reasonable: ture
  support-methods-arguments: true
  params: count=countSql
#logging:
#  config:
#    classpath: logback-spring.xml
#配置短信验证信息
phonecode:
  businessId: 165354
  secretId: 156432
  secretKey: 153431
  API_URl: https://sms.dun.163yun.com/v2/sendsms
  templateId: 1000
